# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 18:54
from __future__ import unicode_literals

from django.db import migrations

def create_superuser(apps, schema_editor):
    from django.contrib.auth.models import User, Group

    user = User.objects.create_superuser('admin_init', '', 'mdcsnist')
    user.save()

    print('user','admin','created')

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
